// Code generated by "stringer -type=rkind"; DO NOT EDIT.

package tgbot

import "fmt"

const (
	_rkind_name_0 = "KindMessageKindEditedMessage"
	_rkind_name_1 = "KindChannelPost"
	_rkind_name_2 = "KindEditedChannelPost"
	_rkind_name_3 = "KindInlineQuery"
	_rkind_name_4 = "KindCallbackQuery"
	_rkind_name_5 = "KindChosenInlineResult"
	_rkind_name_6 = "KindShippingQuery"
	_rkind_name_7 = "KindPreCheckoutQuery"
	_rkind_name_8 = "KindAll"
)

var (
	_rkind_index_0 = [...]uint8{0, 11, 28}
	_rkind_index_1 = [...]uint8{0, 15}
	_rkind_index_2 = [...]uint8{0, 21}
	_rkind_index_3 = [...]uint8{0, 15}
	_rkind_index_4 = [...]uint8{0, 17}
	_rkind_index_5 = [...]uint8{0, 22}
	_rkind_index_6 = [...]uint8{0, 17}
	_rkind_index_7 = [...]uint8{0, 20}
	_rkind_index_8 = [...]uint8{0, 7}
)

func (i rkind) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _rkind_name_0[_rkind_index_0[i]:_rkind_index_0[i+1]]
	case i == 4:
		return _rkind_name_1
	case i == 8:
		return _rkind_name_2
	case i == 16:
		return _rkind_name_3
	case i == 32:
		return _rkind_name_4
	case i == 64:
		return _rkind_name_5
	case i == 128:
		return _rkind_name_6
	case i == 256:
		return _rkind_name_7
	case i == 511:
		return _rkind_name_8
	default:
		return fmt.Sprintf("rkind(%d)", i)
	}
}
