// Code generated by go-swagger; DO NOT EDIT.

package callbacks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/olebedev/go-tgbot/models"
)

// NewAnswerCallbackQueryParams creates a new AnswerCallbackQueryParams object
// with the default values initialized.
func NewAnswerCallbackQueryParams() *AnswerCallbackQueryParams {
	var ()
	return &AnswerCallbackQueryParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewAnswerCallbackQueryParamsWithTimeout creates a new AnswerCallbackQueryParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewAnswerCallbackQueryParamsWithTimeout(timeout time.Duration) *AnswerCallbackQueryParams {
	var ()
	return &AnswerCallbackQueryParams{

		timeout: timeout,
	}
}

// NewAnswerCallbackQueryParamsWithContext creates a new AnswerCallbackQueryParams object
// with the default values initialized, and the ability to set a context for a request
func NewAnswerCallbackQueryParamsWithContext(ctx context.Context) *AnswerCallbackQueryParams {
	var ()
	return &AnswerCallbackQueryParams{

		Context: ctx,
	}
}

// NewAnswerCallbackQueryParamsWithHTTPClient creates a new AnswerCallbackQueryParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewAnswerCallbackQueryParamsWithHTTPClient(client *http.Client) *AnswerCallbackQueryParams {
	var ()
	return &AnswerCallbackQueryParams{
		HTTPClient: client,
	}
}

/*AnswerCallbackQueryParams contains all the parameters to send to the API endpoint
for the answer callback query operation typically these are written to a http.Request
*/
type AnswerCallbackQueryParams struct {

	/*Body*/
	Body *models.AnswerCallbackQueryBody
	/*Token
	  bot's token to authorize the request

	*/
	Token *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the answer callback query params
func (o *AnswerCallbackQueryParams) WithTimeout(timeout time.Duration) *AnswerCallbackQueryParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the answer callback query params
func (o *AnswerCallbackQueryParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the answer callback query params
func (o *AnswerCallbackQueryParams) WithContext(ctx context.Context) *AnswerCallbackQueryParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the answer callback query params
func (o *AnswerCallbackQueryParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the answer callback query params
func (o *AnswerCallbackQueryParams) WithHTTPClient(client *http.Client) *AnswerCallbackQueryParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the answer callback query params
func (o *AnswerCallbackQueryParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the answer callback query params
func (o *AnswerCallbackQueryParams) WithBody(body *models.AnswerCallbackQueryBody) *AnswerCallbackQueryParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the answer callback query params
func (o *AnswerCallbackQueryParams) SetBody(body *models.AnswerCallbackQueryBody) {
	o.Body = body
}

// WithToken adds the token to the answer callback query params
func (o *AnswerCallbackQueryParams) WithToken(token *string) *AnswerCallbackQueryParams {
	o.SetToken(token)
	return o
}

// SetToken adds the token to the answer callback query params
func (o *AnswerCallbackQueryParams) SetToken(token *string) {
	o.Token = token
}

// WriteToRequest writes these params to a swagger request
func (o *AnswerCallbackQueryParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if o.Token != nil {

		// path param token
		if err := r.SetPathParam("token", *o.Token); err != nil {
			return err
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
