// Code generated by go-swagger; DO NOT EDIT.

package stickers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/olebedev/go-tgbot/models"
)

// AddStickerToSetReader is a Reader for the AddStickerToSet structure.
type AddStickerToSetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AddStickerToSetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewAddStickerToSetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewAddStickerToSetBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewAddStickerToSetUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewAddStickerToSetForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewAddStickerToSetNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 420:
		result := NewAddStickerToSetEnhanceYourCalm()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewAddStickerToSetInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewAddStickerToSetOK creates a AddStickerToSetOK with default headers values
func NewAddStickerToSetOK() *AddStickerToSetOK {
	return &AddStickerToSetOK{}
}

/*AddStickerToSetOK handles this case with default header values.

AddStickerToSetOK add sticker to set o k
*/
type AddStickerToSetOK struct {
	Payload *models.ResponseBool
}

func (o *AddStickerToSetOK) Error() string {
	return fmt.Sprintf("[POST /bot{token}/addStickerToSet][%d] addStickerToSetOK  %+v", 200, o.Payload)
}

func (o *AddStickerToSetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseBool)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAddStickerToSetBadRequest creates a AddStickerToSetBadRequest with default headers values
func NewAddStickerToSetBadRequest() *AddStickerToSetBadRequest {
	return &AddStickerToSetBadRequest{}
}

/*AddStickerToSetBadRequest handles this case with default header values.

Bad Request
*/
type AddStickerToSetBadRequest struct {
	Payload *models.Error
}

func (o *AddStickerToSetBadRequest) Error() string {
	return fmt.Sprintf("[POST /bot{token}/addStickerToSet][%d] addStickerToSetBadRequest  %+v", 400, o.Payload)
}

func (o *AddStickerToSetBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAddStickerToSetUnauthorized creates a AddStickerToSetUnauthorized with default headers values
func NewAddStickerToSetUnauthorized() *AddStickerToSetUnauthorized {
	return &AddStickerToSetUnauthorized{}
}

/*AddStickerToSetUnauthorized handles this case with default header values.

Unauthorized
*/
type AddStickerToSetUnauthorized struct {
	Payload *models.Error
}

func (o *AddStickerToSetUnauthorized) Error() string {
	return fmt.Sprintf("[POST /bot{token}/addStickerToSet][%d] addStickerToSetUnauthorized  %+v", 401, o.Payload)
}

func (o *AddStickerToSetUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAddStickerToSetForbidden creates a AddStickerToSetForbidden with default headers values
func NewAddStickerToSetForbidden() *AddStickerToSetForbidden {
	return &AddStickerToSetForbidden{}
}

/*AddStickerToSetForbidden handles this case with default header values.

Forbidden
*/
type AddStickerToSetForbidden struct {
	Payload *models.Error
}

func (o *AddStickerToSetForbidden) Error() string {
	return fmt.Sprintf("[POST /bot{token}/addStickerToSet][%d] addStickerToSetForbidden  %+v", 403, o.Payload)
}

func (o *AddStickerToSetForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAddStickerToSetNotFound creates a AddStickerToSetNotFound with default headers values
func NewAddStickerToSetNotFound() *AddStickerToSetNotFound {
	return &AddStickerToSetNotFound{}
}

/*AddStickerToSetNotFound handles this case with default header values.

Not Found
*/
type AddStickerToSetNotFound struct {
	Payload *models.Error
}

func (o *AddStickerToSetNotFound) Error() string {
	return fmt.Sprintf("[POST /bot{token}/addStickerToSet][%d] addStickerToSetNotFound  %+v", 404, o.Payload)
}

func (o *AddStickerToSetNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAddStickerToSetEnhanceYourCalm creates a AddStickerToSetEnhanceYourCalm with default headers values
func NewAddStickerToSetEnhanceYourCalm() *AddStickerToSetEnhanceYourCalm {
	return &AddStickerToSetEnhanceYourCalm{}
}

/*AddStickerToSetEnhanceYourCalm handles this case with default header values.

Flood
*/
type AddStickerToSetEnhanceYourCalm struct {
	Payload *models.Error
}

func (o *AddStickerToSetEnhanceYourCalm) Error() string {
	return fmt.Sprintf("[POST /bot{token}/addStickerToSet][%d] addStickerToSetEnhanceYourCalm  %+v", 420, o.Payload)
}

func (o *AddStickerToSetEnhanceYourCalm) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAddStickerToSetInternalServerError creates a AddStickerToSetInternalServerError with default headers values
func NewAddStickerToSetInternalServerError() *AddStickerToSetInternalServerError {
	return &AddStickerToSetInternalServerError{}
}

/*AddStickerToSetInternalServerError handles this case with default header values.

Internal
*/
type AddStickerToSetInternalServerError struct {
	Payload *models.Error
}

func (o *AddStickerToSetInternalServerError) Error() string {
	return fmt.Sprintf("[POST /bot{token}/addStickerToSet][%d] addStickerToSetInternalServerError  %+v", 500, o.Payload)
}

func (o *AddStickerToSetInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
