// Code generated by go-swagger; DO NOT EDIT.

package stickers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewUploadStickerFileParams creates a new UploadStickerFileParams object
// with the default values initialized.
func NewUploadStickerFileParams() *UploadStickerFileParams {
	var ()
	return &UploadStickerFileParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUploadStickerFileParamsWithTimeout creates a new UploadStickerFileParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUploadStickerFileParamsWithTimeout(timeout time.Duration) *UploadStickerFileParams {
	var ()
	return &UploadStickerFileParams{

		timeout: timeout,
	}
}

// NewUploadStickerFileParamsWithContext creates a new UploadStickerFileParams object
// with the default values initialized, and the ability to set a context for a request
func NewUploadStickerFileParamsWithContext(ctx context.Context) *UploadStickerFileParams {
	var ()
	return &UploadStickerFileParams{

		Context: ctx,
	}
}

// NewUploadStickerFileParamsWithHTTPClient creates a new UploadStickerFileParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUploadStickerFileParamsWithHTTPClient(client *http.Client) *UploadStickerFileParams {
	var ()
	return &UploadStickerFileParams{
		HTTPClient: client,
	}
}

/*UploadStickerFileParams contains all the parameters to send to the API endpoint
for the upload sticker file operation typically these are written to a http.Request
*/
type UploadStickerFileParams struct {

	/*PngSticker*/
	PngSticker runtime.NamedReadCloser
	/*Token
	  bot's token to authorize the request

	*/
	Token *string
	/*UserID*/
	UserID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the upload sticker file params
func (o *UploadStickerFileParams) WithTimeout(timeout time.Duration) *UploadStickerFileParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the upload sticker file params
func (o *UploadStickerFileParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the upload sticker file params
func (o *UploadStickerFileParams) WithContext(ctx context.Context) *UploadStickerFileParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the upload sticker file params
func (o *UploadStickerFileParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the upload sticker file params
func (o *UploadStickerFileParams) WithHTTPClient(client *http.Client) *UploadStickerFileParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the upload sticker file params
func (o *UploadStickerFileParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithPngSticker adds the pngSticker to the upload sticker file params
func (o *UploadStickerFileParams) WithPngSticker(pngSticker runtime.NamedReadCloser) *UploadStickerFileParams {
	o.SetPngSticker(pngSticker)
	return o
}

// SetPngSticker adds the pngSticker to the upload sticker file params
func (o *UploadStickerFileParams) SetPngSticker(pngSticker runtime.NamedReadCloser) {
	o.PngSticker = pngSticker
}

// WithToken adds the token to the upload sticker file params
func (o *UploadStickerFileParams) WithToken(token *string) *UploadStickerFileParams {
	o.SetToken(token)
	return o
}

// SetToken adds the token to the upload sticker file params
func (o *UploadStickerFileParams) SetToken(token *string) {
	o.Token = token
}

// WithUserID adds the userID to the upload sticker file params
func (o *UploadStickerFileParams) WithUserID(userID int64) *UploadStickerFileParams {
	o.SetUserID(userID)
	return o
}

// SetUserID adds the userId to the upload sticker file params
func (o *UploadStickerFileParams) SetUserID(userID int64) {
	o.UserID = userID
}

// WriteToRequest writes these params to a swagger request
func (o *UploadStickerFileParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// form file param png_sticker
	if err := r.SetFileParam("png_sticker", o.PngSticker); err != nil {
		return err
	}

	if o.Token != nil {

		// path param token
		if err := r.SetPathParam("token", *o.Token); err != nil {
			return err
		}

	}

	// form param user_id
	frUserID := o.UserID
	fUserID := swag.FormatInt64(frUserID)
	if fUserID != "" {
		if err := r.SetFormParam("user_id", fUserID); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
