package games

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/olebedev/go-tgbot/models"
)

// GetGameHighScoresReader is a Reader for the GetGameHighScores structure.
type GetGameHighScoresReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetGameHighScoresReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetGameHighScoresOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewGetGameHighScoresBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetGameHighScoresOK creates a GetGameHighScoresOK with default headers values
func NewGetGameHighScoresOK() *GetGameHighScoresOK {
	return &GetGameHighScoresOK{}
}

/*GetGameHighScoresOK handles this case with default header values.

GetGameHighScoresOK get game high scores o k
*/
type GetGameHighScoresOK struct {
	Payload GetGameHighScoresOKBody
}

func (o *GetGameHighScoresOK) Error() string {
	return fmt.Sprintf("[GET /bot{token}/getGameHighScores][%d] getGameHighScoresOK  %+v", 200, o.Payload)
}

func (o *GetGameHighScoresOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetGameHighScoresBadRequest creates a GetGameHighScoresBadRequest with default headers values
func NewGetGameHighScoresBadRequest() *GetGameHighScoresBadRequest {
	return &GetGameHighScoresBadRequest{}
}

/*GetGameHighScoresBadRequest handles this case with default header values.

Error
*/
type GetGameHighScoresBadRequest struct {
	Payload *models.Error
}

func (o *GetGameHighScoresBadRequest) Error() string {
	return fmt.Sprintf("[GET /bot{token}/getGameHighScores][%d] getGameHighScoresBadRequest  %+v", 400, o.Payload)
}

func (o *GetGameHighScoresBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*GetGameHighScoresOKBody get game high scores o k body
swagger:model GetGameHighScoresOKBody
*/
type GetGameHighScoresOKBody struct {

	// description
	// Required: true
	Description *string `json:"description"`

	// error code
	// Required: true
	ErrorCode *int64 `json:"error_code"`

	// ok
	// Required: true
	Ok *bool `json:"ok"`

	// result
	// Required: true
	Result *models.GameHighScore `json:"result"`
}
