// Code generated by go-swagger; DO NOT EDIT.

package messages

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/olebedev/go-tgbot/models"
)

// NewEditMessageReplyMarkupParams creates a new EditMessageReplyMarkupParams object
// with the default values initialized.
func NewEditMessageReplyMarkupParams() *EditMessageReplyMarkupParams {
	var ()
	return &EditMessageReplyMarkupParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewEditMessageReplyMarkupParamsWithTimeout creates a new EditMessageReplyMarkupParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewEditMessageReplyMarkupParamsWithTimeout(timeout time.Duration) *EditMessageReplyMarkupParams {
	var ()
	return &EditMessageReplyMarkupParams{

		timeout: timeout,
	}
}

// NewEditMessageReplyMarkupParamsWithContext creates a new EditMessageReplyMarkupParams object
// with the default values initialized, and the ability to set a context for a request
func NewEditMessageReplyMarkupParamsWithContext(ctx context.Context) *EditMessageReplyMarkupParams {
	var ()
	return &EditMessageReplyMarkupParams{

		Context: ctx,
	}
}

// NewEditMessageReplyMarkupParamsWithHTTPClient creates a new EditMessageReplyMarkupParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewEditMessageReplyMarkupParamsWithHTTPClient(client *http.Client) *EditMessageReplyMarkupParams {
	var ()
	return &EditMessageReplyMarkupParams{
		HTTPClient: client,
	}
}

/*EditMessageReplyMarkupParams contains all the parameters to send to the API endpoint
for the edit message reply markup operation typically these are written to a http.Request
*/
type EditMessageReplyMarkupParams struct {

	/*Body*/
	Body *models.EditMessageReplyMarkupBody
	/*Token
	  bot's token to authorize the request

	*/
	Token *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the edit message reply markup params
func (o *EditMessageReplyMarkupParams) WithTimeout(timeout time.Duration) *EditMessageReplyMarkupParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the edit message reply markup params
func (o *EditMessageReplyMarkupParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the edit message reply markup params
func (o *EditMessageReplyMarkupParams) WithContext(ctx context.Context) *EditMessageReplyMarkupParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the edit message reply markup params
func (o *EditMessageReplyMarkupParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the edit message reply markup params
func (o *EditMessageReplyMarkupParams) WithHTTPClient(client *http.Client) *EditMessageReplyMarkupParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the edit message reply markup params
func (o *EditMessageReplyMarkupParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the edit message reply markup params
func (o *EditMessageReplyMarkupParams) WithBody(body *models.EditMessageReplyMarkupBody) *EditMessageReplyMarkupParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the edit message reply markup params
func (o *EditMessageReplyMarkupParams) SetBody(body *models.EditMessageReplyMarkupBody) {
	o.Body = body
}

// WithToken adds the token to the edit message reply markup params
func (o *EditMessageReplyMarkupParams) WithToken(token *string) *EditMessageReplyMarkupParams {
	o.SetToken(token)
	return o
}

// SetToken adds the token to the edit message reply markup params
func (o *EditMessageReplyMarkupParams) SetToken(token *string) {
	o.Token = token
}

// WriteToRequest writes these params to a swagger request
func (o *EditMessageReplyMarkupParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if o.Token != nil {

		// path param token
		if err := r.SetPathParam("token", *o.Token); err != nil {
			return err
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
