package attachments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/olebedev/go-tgbot/models"
)

// SendVideoLinkReader is a Reader for the SendVideoLink structure.
type SendVideoLinkReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SendVideoLinkReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewSendVideoLinkOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewSendVideoLinkBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewSendVideoLinkOK creates a SendVideoLinkOK with default headers values
func NewSendVideoLinkOK() *SendVideoLinkOK {
	return &SendVideoLinkOK{}
}

/*SendVideoLinkOK handles this case with default header values.

SendVideoLinkOK send video link o k
*/
type SendVideoLinkOK struct {
	Payload *models.ResponseMessage
}

func (o *SendVideoLinkOK) Error() string {
	return fmt.Sprintf("[POST /bot{token}/sendVideo#link][%d] sendVideoLinkOK  %+v", 200, o.Payload)
}

func (o *SendVideoLinkOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseMessage)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSendVideoLinkBadRequest creates a SendVideoLinkBadRequest with default headers values
func NewSendVideoLinkBadRequest() *SendVideoLinkBadRequest {
	return &SendVideoLinkBadRequest{}
}

/*SendVideoLinkBadRequest handles this case with default header values.

Error
*/
type SendVideoLinkBadRequest struct {
	Payload *models.Error
}

func (o *SendVideoLinkBadRequest) Error() string {
	return fmt.Sprintf("[POST /bot{token}/sendVideo#link][%d] sendVideoLinkBadRequest  %+v", 400, o.Payload)
}

func (o *SendVideoLinkBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*SendVideoLinkBody send video link body
swagger:model SendVideoLinkBody
*/
type SendVideoLinkBody struct {

	// audio
	// Required: true
	Audio *string `json:"audio"`

	// caption
	Caption string `json:"caption,omitempty"`

	// chat id
	// Required: true
	ChatID interface{} `json:"chat_id"`

	// disable notification
	DisableNotification bool `json:"disable_notification,omitempty"`

	// duration
	Duration int64 `json:"duration,omitempty"`

	// height
	Height int64 `json:"height,omitempty"`

	// reply markup
	ReplyMarkup interface{} `json:"reply_markup,omitempty"`

	// reply to message id
	ReplyToMessageID int64 `json:"reply_to_message_id,omitempty"`

	// width
	Width int64 `json:"width,omitempty"`
}
