// Code generated by go-swagger; DO NOT EDIT.

package attachments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/olebedev/go-tgbot/models"
)

// SendStickerLinkReader is a Reader for the SendStickerLink structure.
type SendStickerLinkReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SendStickerLinkReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewSendStickerLinkOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewSendStickerLinkBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewSendStickerLinkUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewSendStickerLinkForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewSendStickerLinkNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 420:
		result := NewSendStickerLinkEnhanceYourCalm()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewSendStickerLinkInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewSendStickerLinkOK creates a SendStickerLinkOK with default headers values
func NewSendStickerLinkOK() *SendStickerLinkOK {
	return &SendStickerLinkOK{}
}

/*SendStickerLinkOK handles this case with default header values.

SendStickerLinkOK send sticker link o k
*/
type SendStickerLinkOK struct {
	Payload *models.ResponseMessage
}

func (o *SendStickerLinkOK) Error() string {
	return fmt.Sprintf("[POST /bot{token}/sendSticker#link][%d] sendStickerLinkOK  %+v", 200, o.Payload)
}

func (o *SendStickerLinkOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseMessage)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSendStickerLinkBadRequest creates a SendStickerLinkBadRequest with default headers values
func NewSendStickerLinkBadRequest() *SendStickerLinkBadRequest {
	return &SendStickerLinkBadRequest{}
}

/*SendStickerLinkBadRequest handles this case with default header values.

Bad Request
*/
type SendStickerLinkBadRequest struct {
	Payload *models.Error
}

func (o *SendStickerLinkBadRequest) Error() string {
	return fmt.Sprintf("[POST /bot{token}/sendSticker#link][%d] sendStickerLinkBadRequest  %+v", 400, o.Payload)
}

func (o *SendStickerLinkBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSendStickerLinkUnauthorized creates a SendStickerLinkUnauthorized with default headers values
func NewSendStickerLinkUnauthorized() *SendStickerLinkUnauthorized {
	return &SendStickerLinkUnauthorized{}
}

/*SendStickerLinkUnauthorized handles this case with default header values.

Unauthorized
*/
type SendStickerLinkUnauthorized struct {
	Payload *models.Error
}

func (o *SendStickerLinkUnauthorized) Error() string {
	return fmt.Sprintf("[POST /bot{token}/sendSticker#link][%d] sendStickerLinkUnauthorized  %+v", 401, o.Payload)
}

func (o *SendStickerLinkUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSendStickerLinkForbidden creates a SendStickerLinkForbidden with default headers values
func NewSendStickerLinkForbidden() *SendStickerLinkForbidden {
	return &SendStickerLinkForbidden{}
}

/*SendStickerLinkForbidden handles this case with default header values.

Forbidden
*/
type SendStickerLinkForbidden struct {
	Payload *models.Error
}

func (o *SendStickerLinkForbidden) Error() string {
	return fmt.Sprintf("[POST /bot{token}/sendSticker#link][%d] sendStickerLinkForbidden  %+v", 403, o.Payload)
}

func (o *SendStickerLinkForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSendStickerLinkNotFound creates a SendStickerLinkNotFound with default headers values
func NewSendStickerLinkNotFound() *SendStickerLinkNotFound {
	return &SendStickerLinkNotFound{}
}

/*SendStickerLinkNotFound handles this case with default header values.

Not Found
*/
type SendStickerLinkNotFound struct {
	Payload *models.Error
}

func (o *SendStickerLinkNotFound) Error() string {
	return fmt.Sprintf("[POST /bot{token}/sendSticker#link][%d] sendStickerLinkNotFound  %+v", 404, o.Payload)
}

func (o *SendStickerLinkNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSendStickerLinkEnhanceYourCalm creates a SendStickerLinkEnhanceYourCalm with default headers values
func NewSendStickerLinkEnhanceYourCalm() *SendStickerLinkEnhanceYourCalm {
	return &SendStickerLinkEnhanceYourCalm{}
}

/*SendStickerLinkEnhanceYourCalm handles this case with default header values.

Flood
*/
type SendStickerLinkEnhanceYourCalm struct {
	Payload *models.Error
}

func (o *SendStickerLinkEnhanceYourCalm) Error() string {
	return fmt.Sprintf("[POST /bot{token}/sendSticker#link][%d] sendStickerLinkEnhanceYourCalm  %+v", 420, o.Payload)
}

func (o *SendStickerLinkEnhanceYourCalm) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSendStickerLinkInternalServerError creates a SendStickerLinkInternalServerError with default headers values
func NewSendStickerLinkInternalServerError() *SendStickerLinkInternalServerError {
	return &SendStickerLinkInternalServerError{}
}

/*SendStickerLinkInternalServerError handles this case with default header values.

Internal
*/
type SendStickerLinkInternalServerError struct {
	Payload *models.Error
}

func (o *SendStickerLinkInternalServerError) Error() string {
	return fmt.Sprintf("[POST /bot{token}/sendSticker#link][%d] sendStickerLinkInternalServerError  %+v", 500, o.Payload)
}

func (o *SendStickerLinkInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
