package attachments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/olebedev/go-tgbot/models"
)

// SendAudioReader is a Reader for the SendAudio structure.
type SendAudioReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SendAudioReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewSendAudioOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewSendAudioOK creates a SendAudioOK with default headers values
func NewSendAudioOK() *SendAudioOK {
	return &SendAudioOK{}
}

/*SendAudioOK handles this case with default header values.

SendAudioOK send audio o k
*/
type SendAudioOK struct {
	Payload SendAudioOKBody
}

func (o *SendAudioOK) Error() string {
	return fmt.Sprintf("[POST /bot{token}/sendAudio][%d] sendAudioOK  %+v", 200, o.Payload)
}

func (o *SendAudioOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*SendAudioOKBody send audio o k body
swagger:model SendAudioOKBody
*/
type SendAudioOKBody struct {

	// description
	// Required: true
	Description *string `json:"description"`

	// error code
	// Required: true
	ErrorCode *int64 `json:"error_code"`

	// ok
	// Required: true
	Ok *bool `json:"ok"`

	// result
	// Required: true
	Result *models.Message `json:"result"`
}
