package attachments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/olebedev/go-tgbot/models"
)

// NewSendLocationParams creates a new SendLocationParams object
// with the default values initialized.
func NewSendLocationParams() *SendLocationParams {
	var ()
	return &SendLocationParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewSendLocationParamsWithTimeout creates a new SendLocationParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewSendLocationParamsWithTimeout(timeout time.Duration) *SendLocationParams {
	var ()
	return &SendLocationParams{

		timeout: timeout,
	}
}

// NewSendLocationParamsWithContext creates a new SendLocationParams object
// with the default values initialized, and the ability to set a context for a request
func NewSendLocationParamsWithContext(ctx context.Context) *SendLocationParams {
	var ()
	return &SendLocationParams{

		Context: ctx,
	}
}

/*SendLocationParams contains all the parameters to send to the API endpoint
for the send location operation typically these are written to a http.Request
*/
type SendLocationParams struct {

	/*Body*/
	Body *models.SendLocationBody
	/*Token
	  bot's token to authorize the request

	*/
	Token *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the send location params
func (o *SendLocationParams) WithTimeout(timeout time.Duration) *SendLocationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the send location params
func (o *SendLocationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the send location params
func (o *SendLocationParams) WithContext(ctx context.Context) *SendLocationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the send location params
func (o *SendLocationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithBody adds the body to the send location params
func (o *SendLocationParams) WithBody(body *models.SendLocationBody) *SendLocationParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the send location params
func (o *SendLocationParams) SetBody(body *models.SendLocationBody) {
	o.Body = body
}

// WithToken adds the token to the send location params
func (o *SendLocationParams) WithToken(token *string) *SendLocationParams {
	o.SetToken(token)
	return o
}

// SetToken adds the token to the send location params
func (o *SendLocationParams) SetToken(token *string) {
	o.Token = token
}

// WriteToRequest writes these params to a swagger request
func (o *SendLocationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if o.Body == nil {
		o.Body = new(models.SendLocationBody)
	}

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	if o.Token != nil {

		// path param token
		if err := r.SetPathParam("token", *o.Token); err != nil {
			return err
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
