package attachments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewSendVoiceLinkParams creates a new SendVoiceLinkParams object
// with the default values initialized.
func NewSendVoiceLinkParams() *SendVoiceLinkParams {
	var ()
	return &SendVoiceLinkParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewSendVoiceLinkParamsWithTimeout creates a new SendVoiceLinkParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewSendVoiceLinkParamsWithTimeout(timeout time.Duration) *SendVoiceLinkParams {
	var ()
	return &SendVoiceLinkParams{

		timeout: timeout,
	}
}

// NewSendVoiceLinkParamsWithContext creates a new SendVoiceLinkParams object
// with the default values initialized, and the ability to set a context for a request
func NewSendVoiceLinkParamsWithContext(ctx context.Context) *SendVoiceLinkParams {
	var ()
	return &SendVoiceLinkParams{

		Context: ctx,
	}
}

/*SendVoiceLinkParams contains all the parameters to send to the API endpoint
for the send voice link operation typically these are written to a http.Request
*/
type SendVoiceLinkParams struct {

	/*Body*/
	Body SendVoiceLinkBody
	/*Token
	  bot's token to authorize the request

	*/
	Token *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the send voice link params
func (o *SendVoiceLinkParams) WithTimeout(timeout time.Duration) *SendVoiceLinkParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the send voice link params
func (o *SendVoiceLinkParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the send voice link params
func (o *SendVoiceLinkParams) WithContext(ctx context.Context) *SendVoiceLinkParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the send voice link params
func (o *SendVoiceLinkParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithBody adds the body to the send voice link params
func (o *SendVoiceLinkParams) WithBody(body SendVoiceLinkBody) *SendVoiceLinkParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the send voice link params
func (o *SendVoiceLinkParams) SetBody(body SendVoiceLinkBody) {
	o.Body = body
}

// WithToken adds the token to the send voice link params
func (o *SendVoiceLinkParams) WithToken(token *string) *SendVoiceLinkParams {
	o.SetToken(token)
	return o
}

// SetToken adds the token to the send voice link params
func (o *SendVoiceLinkParams) SetToken(token *string) {
	o.Token = token
}

// WriteToRequest writes these params to a swagger request
func (o *SendVoiceLinkParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	if o.Token != nil {

		// path param token
		if err := r.SetPathParam("token", *o.Token); err != nil {
			return err
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
