// Code generated by go-swagger; DO NOT EDIT.

package attachments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/olebedev/go-tgbot/models"
)

// NewSendAudioLinkParams creates a new SendAudioLinkParams object
// with the default values initialized.
func NewSendAudioLinkParams() *SendAudioLinkParams {
	var ()
	return &SendAudioLinkParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewSendAudioLinkParamsWithTimeout creates a new SendAudioLinkParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewSendAudioLinkParamsWithTimeout(timeout time.Duration) *SendAudioLinkParams {
	var ()
	return &SendAudioLinkParams{

		timeout: timeout,
	}
}

// NewSendAudioLinkParamsWithContext creates a new SendAudioLinkParams object
// with the default values initialized, and the ability to set a context for a request
func NewSendAudioLinkParamsWithContext(ctx context.Context) *SendAudioLinkParams {
	var ()
	return &SendAudioLinkParams{

		Context: ctx,
	}
}

// NewSendAudioLinkParamsWithHTTPClient creates a new SendAudioLinkParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewSendAudioLinkParamsWithHTTPClient(client *http.Client) *SendAudioLinkParams {
	var ()
	return &SendAudioLinkParams{
		HTTPClient: client,
	}
}

/*SendAudioLinkParams contains all the parameters to send to the API endpoint
for the send audio link operation typically these are written to a http.Request
*/
type SendAudioLinkParams struct {

	/*Body*/
	Body *models.SendAudioLinkBody
	/*Token
	  bot's token to authorize the request

	*/
	Token *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the send audio link params
func (o *SendAudioLinkParams) WithTimeout(timeout time.Duration) *SendAudioLinkParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the send audio link params
func (o *SendAudioLinkParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the send audio link params
func (o *SendAudioLinkParams) WithContext(ctx context.Context) *SendAudioLinkParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the send audio link params
func (o *SendAudioLinkParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the send audio link params
func (o *SendAudioLinkParams) WithHTTPClient(client *http.Client) *SendAudioLinkParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the send audio link params
func (o *SendAudioLinkParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the send audio link params
func (o *SendAudioLinkParams) WithBody(body *models.SendAudioLinkBody) *SendAudioLinkParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the send audio link params
func (o *SendAudioLinkParams) SetBody(body *models.SendAudioLinkBody) {
	o.Body = body
}

// WithToken adds the token to the send audio link params
func (o *SendAudioLinkParams) WithToken(token *string) *SendAudioLinkParams {
	o.SetToken(token)
	return o
}

// SetToken adds the token to the send audio link params
func (o *SendAudioLinkParams) SetToken(token *string) {
	o.Token = token
}

// WriteToRequest writes these params to a swagger request
func (o *SendAudioLinkParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if o.Token != nil {

		// path param token
		if err := r.SetPathParam("token", *o.Token); err != nil {
			return err
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
