package attachments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/olebedev/go-tgbot/models"
)

// SendContactReader is a Reader for the SendContact structure.
type SendContactReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SendContactReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewSendContactOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewSendContactBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewSendContactOK creates a SendContactOK with default headers values
func NewSendContactOK() *SendContactOK {
	return &SendContactOK{}
}

/*SendContactOK handles this case with default header values.

SendContactOK send contact o k
*/
type SendContactOK struct {
	Payload *models.ResponseMessage
}

func (o *SendContactOK) Error() string {
	return fmt.Sprintf("[POST /bot{token}/sendContact][%d] sendContactOK  %+v", 200, o.Payload)
}

func (o *SendContactOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseMessage)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSendContactBadRequest creates a SendContactBadRequest with default headers values
func NewSendContactBadRequest() *SendContactBadRequest {
	return &SendContactBadRequest{}
}

/*SendContactBadRequest handles this case with default header values.

Error
*/
type SendContactBadRequest struct {
	Payload *models.Error
}

func (o *SendContactBadRequest) Error() string {
	return fmt.Sprintf("[POST /bot{token}/sendContact][%d] sendContactBadRequest  %+v", 400, o.Payload)
}

func (o *SendContactBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
