package attachments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/olebedev/go-tgbot/models"
)

// SendStickerReader is a Reader for the SendSticker structure.
type SendStickerReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SendStickerReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewSendStickerOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewSendStickerOK creates a SendStickerOK with default headers values
func NewSendStickerOK() *SendStickerOK {
	return &SendStickerOK{}
}

/*SendStickerOK handles this case with default header values.

SendStickerOK send sticker o k
*/
type SendStickerOK struct {
	Payload SendStickerOKBody
}

func (o *SendStickerOK) Error() string {
	return fmt.Sprintf("[POST /bot{token}/sendSticker][%d] sendStickerOK  %+v", 200, o.Payload)
}

func (o *SendStickerOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*SendStickerOKBody send sticker o k body
swagger:model SendStickerOKBody
*/
type SendStickerOKBody struct {

	// description
	// Required: true
	Description *string `json:"description"`

	// error code
	// Required: true
	ErrorCode *int64 `json:"error_code"`

	// ok
	// Required: true
	Ok *bool `json:"ok"`

	// result
	// Required: true
	Result *models.Message `json:"result"`
}
