// Code generated by go-swagger; DO NOT EDIT.

package chats

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetChatAdministratorsParams creates a new GetChatAdministratorsParams object
// with the default values initialized.
func NewGetChatAdministratorsParams() *GetChatAdministratorsParams {
	var ()
	return &GetChatAdministratorsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetChatAdministratorsParamsWithTimeout creates a new GetChatAdministratorsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetChatAdministratorsParamsWithTimeout(timeout time.Duration) *GetChatAdministratorsParams {
	var ()
	return &GetChatAdministratorsParams{

		timeout: timeout,
	}
}

// NewGetChatAdministratorsParamsWithContext creates a new GetChatAdministratorsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetChatAdministratorsParamsWithContext(ctx context.Context) *GetChatAdministratorsParams {
	var ()
	return &GetChatAdministratorsParams{

		Context: ctx,
	}
}

// NewGetChatAdministratorsParamsWithHTTPClient creates a new GetChatAdministratorsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetChatAdministratorsParamsWithHTTPClient(client *http.Client) *GetChatAdministratorsParams {
	var ()
	return &GetChatAdministratorsParams{
		HTTPClient: client,
	}
}

/*GetChatAdministratorsParams contains all the parameters to send to the API endpoint
for the get chat administrators operation typically these are written to a http.Request
*/
type GetChatAdministratorsParams struct {

	/*ChatID*/
	ChatID string
	/*Token
	  bot's token to authorize the request

	*/
	Token *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get chat administrators params
func (o *GetChatAdministratorsParams) WithTimeout(timeout time.Duration) *GetChatAdministratorsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get chat administrators params
func (o *GetChatAdministratorsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get chat administrators params
func (o *GetChatAdministratorsParams) WithContext(ctx context.Context) *GetChatAdministratorsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get chat administrators params
func (o *GetChatAdministratorsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get chat administrators params
func (o *GetChatAdministratorsParams) WithHTTPClient(client *http.Client) *GetChatAdministratorsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get chat administrators params
func (o *GetChatAdministratorsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithChatID adds the chatID to the get chat administrators params
func (o *GetChatAdministratorsParams) WithChatID(chatID string) *GetChatAdministratorsParams {
	o.SetChatID(chatID)
	return o
}

// SetChatID adds the chatId to the get chat administrators params
func (o *GetChatAdministratorsParams) SetChatID(chatID string) {
	o.ChatID = chatID
}

// WithToken adds the token to the get chat administrators params
func (o *GetChatAdministratorsParams) WithToken(token *string) *GetChatAdministratorsParams {
	o.SetToken(token)
	return o
}

// SetToken adds the token to the get chat administrators params
func (o *GetChatAdministratorsParams) SetToken(token *string) {
	o.Token = token
}

// WriteToRequest writes these params to a swagger request
func (o *GetChatAdministratorsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param chat_id
	qrChatID := o.ChatID
	qChatID := qrChatID
	if qChatID != "" {
		if err := r.SetQueryParam("chat_id", qChatID); err != nil {
			return err
		}
	}

	if o.Token != nil {

		// path param token
		if err := r.SetPathParam("token", *o.Token); err != nil {
			return err
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
