package chats

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewKickChatMemberParams creates a new KickChatMemberParams object
// with the default values initialized.
func NewKickChatMemberParams() *KickChatMemberParams {
	var ()
	return &KickChatMemberParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewKickChatMemberParamsWithTimeout creates a new KickChatMemberParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewKickChatMemberParamsWithTimeout(timeout time.Duration) *KickChatMemberParams {
	var ()
	return &KickChatMemberParams{

		timeout: timeout,
	}
}

// NewKickChatMemberParamsWithContext creates a new KickChatMemberParams object
// with the default values initialized, and the ability to set a context for a request
func NewKickChatMemberParamsWithContext(ctx context.Context) *KickChatMemberParams {
	var ()
	return &KickChatMemberParams{

		Context: ctx,
	}
}

/*KickChatMemberParams contains all the parameters to send to the API endpoint
for the kick chat member operation typically these are written to a http.Request
*/
type KickChatMemberParams struct {

	/*ChatID*/
	ChatID string
	/*Token
	  bot's token to authorize the request

	*/
	Token *string
	/*UserID*/
	UserID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the kick chat member params
func (o *KickChatMemberParams) WithTimeout(timeout time.Duration) *KickChatMemberParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the kick chat member params
func (o *KickChatMemberParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the kick chat member params
func (o *KickChatMemberParams) WithContext(ctx context.Context) *KickChatMemberParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the kick chat member params
func (o *KickChatMemberParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithChatID adds the chatID to the kick chat member params
func (o *KickChatMemberParams) WithChatID(chatID string) *KickChatMemberParams {
	o.SetChatID(chatID)
	return o
}

// SetChatID adds the chatId to the kick chat member params
func (o *KickChatMemberParams) SetChatID(chatID string) {
	o.ChatID = chatID
}

// WithToken adds the token to the kick chat member params
func (o *KickChatMemberParams) WithToken(token *string) *KickChatMemberParams {
	o.SetToken(token)
	return o
}

// SetToken adds the token to the kick chat member params
func (o *KickChatMemberParams) SetToken(token *string) {
	o.Token = token
}

// WithUserID adds the userID to the kick chat member params
func (o *KickChatMemberParams) WithUserID(userID string) *KickChatMemberParams {
	o.SetUserID(userID)
	return o
}

// SetUserID adds the userId to the kick chat member params
func (o *KickChatMemberParams) SetUserID(userID string) {
	o.UserID = userID
}

// WriteToRequest writes these params to a swagger request
func (o *KickChatMemberParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// query param chat_id
	qrChatID := o.ChatID
	qChatID := qrChatID
	if qChatID != "" {
		if err := r.SetQueryParam("chat_id", qChatID); err != nil {
			return err
		}
	}

	if o.Token != nil {

		// path param token
		if err := r.SetPathParam("token", *o.Token); err != nil {
			return err
		}

	}

	// query param user_id
	qrUserID := o.UserID
	qUserID := qrUserID
	if qUserID != "" {
		if err := r.SetQueryParam("user_id", qUserID); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
