// Code generated by go-swagger; DO NOT EDIT.

package chats

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewLeaveChatParams creates a new LeaveChatParams object
// with the default values initialized.
func NewLeaveChatParams() *LeaveChatParams {
	var ()
	return &LeaveChatParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewLeaveChatParamsWithTimeout creates a new LeaveChatParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewLeaveChatParamsWithTimeout(timeout time.Duration) *LeaveChatParams {
	var ()
	return &LeaveChatParams{

		timeout: timeout,
	}
}

// NewLeaveChatParamsWithContext creates a new LeaveChatParams object
// with the default values initialized, and the ability to set a context for a request
func NewLeaveChatParamsWithContext(ctx context.Context) *LeaveChatParams {
	var ()
	return &LeaveChatParams{

		Context: ctx,
	}
}

// NewLeaveChatParamsWithHTTPClient creates a new LeaveChatParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewLeaveChatParamsWithHTTPClient(client *http.Client) *LeaveChatParams {
	var ()
	return &LeaveChatParams{
		HTTPClient: client,
	}
}

/*LeaveChatParams contains all the parameters to send to the API endpoint
for the leave chat operation typically these are written to a http.Request
*/
type LeaveChatParams struct {

	/*ChatID*/
	ChatID string
	/*Token
	  bot's token to authorize the request

	*/
	Token *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the leave chat params
func (o *LeaveChatParams) WithTimeout(timeout time.Duration) *LeaveChatParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the leave chat params
func (o *LeaveChatParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the leave chat params
func (o *LeaveChatParams) WithContext(ctx context.Context) *LeaveChatParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the leave chat params
func (o *LeaveChatParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the leave chat params
func (o *LeaveChatParams) WithHTTPClient(client *http.Client) *LeaveChatParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the leave chat params
func (o *LeaveChatParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithChatID adds the chatID to the leave chat params
func (o *LeaveChatParams) WithChatID(chatID string) *LeaveChatParams {
	o.SetChatID(chatID)
	return o
}

// SetChatID adds the chatId to the leave chat params
func (o *LeaveChatParams) SetChatID(chatID string) {
	o.ChatID = chatID
}

// WithToken adds the token to the leave chat params
func (o *LeaveChatParams) WithToken(token *string) *LeaveChatParams {
	o.SetToken(token)
	return o
}

// SetToken adds the token to the leave chat params
func (o *LeaveChatParams) SetToken(token *string) {
	o.Token = token
}

// WriteToRequest writes these params to a swagger request
func (o *LeaveChatParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param chat_id
	qrChatID := o.ChatID
	qChatID := qrChatID
	if qChatID != "" {
		if err := r.SetQueryParam("chat_id", qChatID); err != nil {
			return err
		}
	}

	if o.Token != nil {

		// path param token
		if err := r.SetPathParam("token", *o.Token); err != nil {
			return err
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
