package chats

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// SendChatActionReader is a Reader for the SendChatAction structure.
type SendChatActionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SendChatActionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewSendChatActionOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewSendChatActionOK creates a SendChatActionOK with default headers values
func NewSendChatActionOK() *SendChatActionOK {
	return &SendChatActionOK{}
}

/*SendChatActionOK handles this case with default header values.

SendChatActionOK send chat action o k
*/
type SendChatActionOK struct {
	Payload SendChatActionOKBody
}

func (o *SendChatActionOK) Error() string {
	return fmt.Sprintf("[GET /bot{token}/sendChatAction][%d] sendChatActionOK  %+v", 200, o.Payload)
}

func (o *SendChatActionOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*SendChatActionOKBody send chat action o k body
swagger:model SendChatActionOKBody
*/
type SendChatActionOKBody struct {

	// description
	// Required: true
	Description *string `json:"description"`

	// error code
	// Required: true
	ErrorCode *int64 `json:"error_code"`

	// ok
	// Required: true
	Ok *bool `json:"ok"`

	// result
	// Required: true
	Result *bool `json:"result"`
}
