// Code generated by go-swagger; DO NOT EDIT.

package chats

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/olebedev/go-tgbot/models"
)

// SetChatStickerSetReader is a Reader for the SetChatStickerSet structure.
type SetChatStickerSetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SetChatStickerSetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewSetChatStickerSetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewSetChatStickerSetBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewSetChatStickerSetUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewSetChatStickerSetForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewSetChatStickerSetNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 420:
		result := NewSetChatStickerSetEnhanceYourCalm()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewSetChatStickerSetInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewSetChatStickerSetOK creates a SetChatStickerSetOK with default headers values
func NewSetChatStickerSetOK() *SetChatStickerSetOK {
	return &SetChatStickerSetOK{}
}

/*SetChatStickerSetOK handles this case with default header values.

SetChatStickerSetOK set chat sticker set o k
*/
type SetChatStickerSetOK struct {
	Payload *models.ResponseBool
}

func (o *SetChatStickerSetOK) Error() string {
	return fmt.Sprintf("[GET /bot{token}/setChatStickerSet][%d] setChatStickerSetOK  %+v", 200, o.Payload)
}

func (o *SetChatStickerSetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseBool)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSetChatStickerSetBadRequest creates a SetChatStickerSetBadRequest with default headers values
func NewSetChatStickerSetBadRequest() *SetChatStickerSetBadRequest {
	return &SetChatStickerSetBadRequest{}
}

/*SetChatStickerSetBadRequest handles this case with default header values.

Bad Request
*/
type SetChatStickerSetBadRequest struct {
	Payload *models.Error
}

func (o *SetChatStickerSetBadRequest) Error() string {
	return fmt.Sprintf("[GET /bot{token}/setChatStickerSet][%d] setChatStickerSetBadRequest  %+v", 400, o.Payload)
}

func (o *SetChatStickerSetBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSetChatStickerSetUnauthorized creates a SetChatStickerSetUnauthorized with default headers values
func NewSetChatStickerSetUnauthorized() *SetChatStickerSetUnauthorized {
	return &SetChatStickerSetUnauthorized{}
}

/*SetChatStickerSetUnauthorized handles this case with default header values.

Unauthorized
*/
type SetChatStickerSetUnauthorized struct {
	Payload *models.Error
}

func (o *SetChatStickerSetUnauthorized) Error() string {
	return fmt.Sprintf("[GET /bot{token}/setChatStickerSet][%d] setChatStickerSetUnauthorized  %+v", 401, o.Payload)
}

func (o *SetChatStickerSetUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSetChatStickerSetForbidden creates a SetChatStickerSetForbidden with default headers values
func NewSetChatStickerSetForbidden() *SetChatStickerSetForbidden {
	return &SetChatStickerSetForbidden{}
}

/*SetChatStickerSetForbidden handles this case with default header values.

Forbidden
*/
type SetChatStickerSetForbidden struct {
	Payload *models.Error
}

func (o *SetChatStickerSetForbidden) Error() string {
	return fmt.Sprintf("[GET /bot{token}/setChatStickerSet][%d] setChatStickerSetForbidden  %+v", 403, o.Payload)
}

func (o *SetChatStickerSetForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSetChatStickerSetNotFound creates a SetChatStickerSetNotFound with default headers values
func NewSetChatStickerSetNotFound() *SetChatStickerSetNotFound {
	return &SetChatStickerSetNotFound{}
}

/*SetChatStickerSetNotFound handles this case with default header values.

Not Found
*/
type SetChatStickerSetNotFound struct {
	Payload *models.Error
}

func (o *SetChatStickerSetNotFound) Error() string {
	return fmt.Sprintf("[GET /bot{token}/setChatStickerSet][%d] setChatStickerSetNotFound  %+v", 404, o.Payload)
}

func (o *SetChatStickerSetNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSetChatStickerSetEnhanceYourCalm creates a SetChatStickerSetEnhanceYourCalm with default headers values
func NewSetChatStickerSetEnhanceYourCalm() *SetChatStickerSetEnhanceYourCalm {
	return &SetChatStickerSetEnhanceYourCalm{}
}

/*SetChatStickerSetEnhanceYourCalm handles this case with default header values.

Flood
*/
type SetChatStickerSetEnhanceYourCalm struct {
	Payload *models.Error
}

func (o *SetChatStickerSetEnhanceYourCalm) Error() string {
	return fmt.Sprintf("[GET /bot{token}/setChatStickerSet][%d] setChatStickerSetEnhanceYourCalm  %+v", 420, o.Payload)
}

func (o *SetChatStickerSetEnhanceYourCalm) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSetChatStickerSetInternalServerError creates a SetChatStickerSetInternalServerError with default headers values
func NewSetChatStickerSetInternalServerError() *SetChatStickerSetInternalServerError {
	return &SetChatStickerSetInternalServerError{}
}

/*SetChatStickerSetInternalServerError handles this case with default header values.

Internal
*/
type SetChatStickerSetInternalServerError struct {
	Payload *models.Error
}

func (o *SetChatStickerSetInternalServerError) Error() string {
	return fmt.Sprintf("[GET /bot{token}/setChatStickerSet][%d] setChatStickerSetInternalServerError  %+v", 500, o.Payload)
}

func (o *SetChatStickerSetInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
