package chats

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/olebedev/go-tgbot/models"
)

// UnbanChatMemberReader is a Reader for the UnbanChatMember structure.
type UnbanChatMemberReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UnbanChatMemberReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewUnbanChatMemberOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewUnbanChatMemberBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewUnbanChatMemberUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewUnbanChatMemberForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewUnbanChatMemberNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 420:
		result := NewUnbanChatMemberEnhanceYourCalm()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewUnbanChatMemberInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewUnbanChatMemberOK creates a UnbanChatMemberOK with default headers values
func NewUnbanChatMemberOK() *UnbanChatMemberOK {
	return &UnbanChatMemberOK{}
}

/*UnbanChatMemberOK handles this case with default header values.

UnbanChatMemberOK unban chat member o k
*/
type UnbanChatMemberOK struct {
	Payload UnbanChatMemberOKBody
}

func (o *UnbanChatMemberOK) Error() string {
	return fmt.Sprintf("[GET /bot{token}/unbanChatMember][%d] unbanChatMemberOK  %+v", 200, o.Payload)
}

func (o *UnbanChatMemberOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUnbanChatMemberBadRequest creates a UnbanChatMemberBadRequest with default headers values
func NewUnbanChatMemberBadRequest() *UnbanChatMemberBadRequest {
	return &UnbanChatMemberBadRequest{}
}

/*UnbanChatMemberBadRequest handles this case with default header values.

Bad Request
*/
type UnbanChatMemberBadRequest struct {
	Payload *models.Error
}

func (o *UnbanChatMemberBadRequest) Error() string {
	return fmt.Sprintf("[GET /bot{token}/unbanChatMember][%d] unbanChatMemberBadRequest  %+v", 400, o.Payload)
}

func (o *UnbanChatMemberBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUnbanChatMemberUnauthorized creates a UnbanChatMemberUnauthorized with default headers values
func NewUnbanChatMemberUnauthorized() *UnbanChatMemberUnauthorized {
	return &UnbanChatMemberUnauthorized{}
}

/*UnbanChatMemberUnauthorized handles this case with default header values.

Unauthorized
*/
type UnbanChatMemberUnauthorized struct {
	Payload *models.Error
}

func (o *UnbanChatMemberUnauthorized) Error() string {
	return fmt.Sprintf("[GET /bot{token}/unbanChatMember][%d] unbanChatMemberUnauthorized  %+v", 401, o.Payload)
}

func (o *UnbanChatMemberUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUnbanChatMemberForbidden creates a UnbanChatMemberForbidden with default headers values
func NewUnbanChatMemberForbidden() *UnbanChatMemberForbidden {
	return &UnbanChatMemberForbidden{}
}

/*UnbanChatMemberForbidden handles this case with default header values.

Forbidden
*/
type UnbanChatMemberForbidden struct {
	Payload *models.Error
}

func (o *UnbanChatMemberForbidden) Error() string {
	return fmt.Sprintf("[GET /bot{token}/unbanChatMember][%d] unbanChatMemberForbidden  %+v", 403, o.Payload)
}

func (o *UnbanChatMemberForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUnbanChatMemberNotFound creates a UnbanChatMemberNotFound with default headers values
func NewUnbanChatMemberNotFound() *UnbanChatMemberNotFound {
	return &UnbanChatMemberNotFound{}
}

/*UnbanChatMemberNotFound handles this case with default header values.

Not Found
*/
type UnbanChatMemberNotFound struct {
	Payload *models.Error
}

func (o *UnbanChatMemberNotFound) Error() string {
	return fmt.Sprintf("[GET /bot{token}/unbanChatMember][%d] unbanChatMemberNotFound  %+v", 404, o.Payload)
}

func (o *UnbanChatMemberNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUnbanChatMemberEnhanceYourCalm creates a UnbanChatMemberEnhanceYourCalm with default headers values
func NewUnbanChatMemberEnhanceYourCalm() *UnbanChatMemberEnhanceYourCalm {
	return &UnbanChatMemberEnhanceYourCalm{}
}

/*UnbanChatMemberEnhanceYourCalm handles this case with default header values.

Flood
*/
type UnbanChatMemberEnhanceYourCalm struct {
	Payload *models.Error
}

func (o *UnbanChatMemberEnhanceYourCalm) Error() string {
	return fmt.Sprintf("[GET /bot{token}/unbanChatMember][%d] unbanChatMemberEnhanceYourCalm  %+v", 420, o.Payload)
}

func (o *UnbanChatMemberEnhanceYourCalm) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUnbanChatMemberInternalServerError creates a UnbanChatMemberInternalServerError with default headers values
func NewUnbanChatMemberInternalServerError() *UnbanChatMemberInternalServerError {
	return &UnbanChatMemberInternalServerError{}
}

/*UnbanChatMemberInternalServerError handles this case with default header values.

Internal
*/
type UnbanChatMemberInternalServerError struct {
	Payload *models.Error
}

func (o *UnbanChatMemberInternalServerError) Error() string {
	return fmt.Sprintf("[GET /bot{token}/unbanChatMember][%d] unbanChatMemberInternalServerError  %+v", 500, o.Payload)
}

func (o *UnbanChatMemberInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*UnbanChatMemberOKBody unban chat member o k body
swagger:model UnbanChatMemberOKBody
*/
type UnbanChatMemberOKBody struct {

	// description
	// Required: true
	Description *string `json:"description"`

	// error code
	// Required: true
	ErrorCode *int64 `json:"error_code"`

	// ok
	// Required: true
	Ok *bool `json:"ok"`

	// result
	// Required: true
	Result *bool `json:"result"`
}

// Validate validates this unban chat member o k body
func (o *UnbanChatMemberOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateDescription(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := o.validateErrorCode(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := o.validateOk(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := o.validateResult(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *UnbanChatMemberOKBody) validateDescription(formats strfmt.Registry) error {

	if err := validate.Required("unbanChatMemberOK"+"."+"description", "body", o.Description); err != nil {
		return err
	}

	return nil
}

func (o *UnbanChatMemberOKBody) validateErrorCode(formats strfmt.Registry) error {

	if err := validate.Required("unbanChatMemberOK"+"."+"error_code", "body", o.ErrorCode); err != nil {
		return err
	}

	return nil
}

func (o *UnbanChatMemberOKBody) validateOk(formats strfmt.Registry) error {

	if err := validate.Required("unbanChatMemberOK"+"."+"ok", "body", o.Ok); err != nil {
		return err
	}

	return nil
}

func (o *UnbanChatMemberOKBody) validateResult(formats strfmt.Registry) error {

	if err := validate.Required("unbanChatMemberOK"+"."+"result", "body", o.Result); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *UnbanChatMemberOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *UnbanChatMemberOKBody) UnmarshalBinary(b []byte) error {
	var res UnbanChatMemberOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
