// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// InlineKeyboardMarkup inline keyboard markup
// swagger:model InlineKeyboardMarkup
type InlineKeyboardMarkup struct {

	// inline keyboard
	InlineKeyboard InlineKeyboardMarkupInlineKeyboard `json:"inline_keyboard"`
}

// Validate validates this inline keyboard markup
func (m *InlineKeyboardMarkup) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *InlineKeyboardMarkup) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *InlineKeyboardMarkup) UnmarshalBinary(b []byte) error {
	var res InlineKeyboardMarkup
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
