package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

// KeyboardButton keyboard button
// swagger:model KeyboardButton
type KeyboardButton struct {

	// request contact
	RequestContact bool `json:"request_contact,omitempty"`

	// request location
	RequestLocation bool `json:"request_location,omitempty"`

	// text
	Text string `json:"text,omitempty"`
}

// Validate validates this keyboard button
func (m *KeyboardButton) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
