// DO NOT EDIT!
// Code generated by ffjson <https://github.com/pquerna/ffjson>
// source: models/pre_checkout_query.go
// DO NOT EDIT!

package models

import (
	"bytes"
	"encoding/json"
	"fmt"
	fflib "github.com/pquerna/ffjson/fflib/v1"
)

func (mj *PreCheckoutQuery) MarshalJSON() ([]byte, error) {
	var buf fflib.Buffer
	if mj == nil {
		buf.WriteString("null")
		return buf.Bytes(), nil
	}
	err := mj.MarshalJSONBuf(&buf)
	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
func (mj *PreCheckoutQuery) MarshalJSONBuf(buf fflib.EncodingBuffer) error {
	if mj == nil {
		buf.WriteString("null")
		return nil
	}
	var err error
	var obj []byte
	_ = obj
	_ = err
	buf.WriteString(`{ `)
	if len(mj.Currency) != 0 {
		buf.WriteString(`"currency":`)
		fflib.WriteJsonString(buf, string(mj.Currency))
		buf.WriteByte(',')
	}
	if mj.From != nil {
		if true {
			/* Struct fall back. type=models.User kind=struct */
			buf.WriteString(`"from":`)
			err = buf.Encode(mj.From)
			if err != nil {
				return err
			}
			buf.WriteByte(',')
		}
	}
	if len(mj.ID) != 0 {
		buf.WriteString(`"id":`)
		fflib.WriteJsonString(buf, string(mj.ID))
		buf.WriteByte(',')
	}
	if len(mj.InvoicePayload) != 0 {
		buf.WriteString(`"invoice_payload":`)
		fflib.WriteJsonString(buf, string(mj.InvoicePayload))
		buf.WriteByte(',')
	}
	if mj.OrderInfo != nil {
		if true {
			buf.WriteString(`"order_info":`)

			{

				err = mj.OrderInfo.MarshalJSONBuf(buf)
				if err != nil {
					return err
				}

			}
			buf.WriteByte(',')
		}
	}
	if len(mj.ShippingOptionID) != 0 {
		buf.WriteString(`"shipping_option_id":`)
		fflib.WriteJsonString(buf, string(mj.ShippingOptionID))
		buf.WriteByte(',')
	}
	if mj.TotalAmount != 0 {
		buf.WriteString(`"total_amount":`)
		fflib.FormatBits2(buf, uint64(mj.TotalAmount), 10, mj.TotalAmount < 0)
		buf.WriteByte(',')
	}
	buf.Rewind(1)
	buf.WriteByte('}')
	return nil
}

const (
	ffj_t_PreCheckoutQuerybase = iota
	ffj_t_PreCheckoutQueryno_such_key

	ffj_t_PreCheckoutQuery_Currency

	ffj_t_PreCheckoutQuery_From

	ffj_t_PreCheckoutQuery_ID

	ffj_t_PreCheckoutQuery_InvoicePayload

	ffj_t_PreCheckoutQuery_OrderInfo

	ffj_t_PreCheckoutQuery_ShippingOptionID

	ffj_t_PreCheckoutQuery_TotalAmount
)

var ffj_key_PreCheckoutQuery_Currency = []byte("currency")

var ffj_key_PreCheckoutQuery_From = []byte("from")

var ffj_key_PreCheckoutQuery_ID = []byte("id")

var ffj_key_PreCheckoutQuery_InvoicePayload = []byte("invoice_payload")

var ffj_key_PreCheckoutQuery_OrderInfo = []byte("order_info")

var ffj_key_PreCheckoutQuery_ShippingOptionID = []byte("shipping_option_id")

var ffj_key_PreCheckoutQuery_TotalAmount = []byte("total_amount")

func (uj *PreCheckoutQuery) UnmarshalJSON(input []byte) error {
	fs := fflib.NewFFLexer(input)
	return uj.UnmarshalJSONFFLexer(fs, fflib.FFParse_map_start)
}

func (uj *PreCheckoutQuery) UnmarshalJSONFFLexer(fs *fflib.FFLexer, state fflib.FFParseState) error {
	var err error = nil
	currentKey := ffj_t_PreCheckoutQuerybase
	_ = currentKey
	tok := fflib.FFTok_init
	wantedTok := fflib.FFTok_init

mainparse:
	for {
		tok = fs.Scan()
		//	println(fmt.Sprintf("debug: tok: %v  state: %v", tok, state))
		if tok == fflib.FFTok_error {
			goto tokerror
		}

		switch state {

		case fflib.FFParse_map_start:
			if tok != fflib.FFTok_left_bracket {
				wantedTok = fflib.FFTok_left_bracket
				goto wrongtokenerror
			}
			state = fflib.FFParse_want_key
			continue

		case fflib.FFParse_after_value:
			if tok == fflib.FFTok_comma {
				state = fflib.FFParse_want_key
			} else if tok == fflib.FFTok_right_bracket {
				goto done
			} else {
				wantedTok = fflib.FFTok_comma
				goto wrongtokenerror
			}

		case fflib.FFParse_want_key:
			// json {} ended. goto exit. woo.
			if tok == fflib.FFTok_right_bracket {
				goto done
			}
			if tok != fflib.FFTok_string {
				wantedTok = fflib.FFTok_string
				goto wrongtokenerror
			}

			kn := fs.Output.Bytes()
			if len(kn) <= 0 {
				// "" case. hrm.
				currentKey = ffj_t_PreCheckoutQueryno_such_key
				state = fflib.FFParse_want_colon
				goto mainparse
			} else {
				switch kn[0] {

				case 'c':

					if bytes.Equal(ffj_key_PreCheckoutQuery_Currency, kn) {
						currentKey = ffj_t_PreCheckoutQuery_Currency
						state = fflib.FFParse_want_colon
						goto mainparse
					}

				case 'f':

					if bytes.Equal(ffj_key_PreCheckoutQuery_From, kn) {
						currentKey = ffj_t_PreCheckoutQuery_From
						state = fflib.FFParse_want_colon
						goto mainparse
					}

				case 'i':

					if bytes.Equal(ffj_key_PreCheckoutQuery_ID, kn) {
						currentKey = ffj_t_PreCheckoutQuery_ID
						state = fflib.FFParse_want_colon
						goto mainparse

					} else if bytes.Equal(ffj_key_PreCheckoutQuery_InvoicePayload, kn) {
						currentKey = ffj_t_PreCheckoutQuery_InvoicePayload
						state = fflib.FFParse_want_colon
						goto mainparse
					}

				case 'o':

					if bytes.Equal(ffj_key_PreCheckoutQuery_OrderInfo, kn) {
						currentKey = ffj_t_PreCheckoutQuery_OrderInfo
						state = fflib.FFParse_want_colon
						goto mainparse
					}

				case 's':

					if bytes.Equal(ffj_key_PreCheckoutQuery_ShippingOptionID, kn) {
						currentKey = ffj_t_PreCheckoutQuery_ShippingOptionID
						state = fflib.FFParse_want_colon
						goto mainparse
					}

				case 't':

					if bytes.Equal(ffj_key_PreCheckoutQuery_TotalAmount, kn) {
						currentKey = ffj_t_PreCheckoutQuery_TotalAmount
						state = fflib.FFParse_want_colon
						goto mainparse
					}

				}

				if fflib.AsciiEqualFold(ffj_key_PreCheckoutQuery_TotalAmount, kn) {
					currentKey = ffj_t_PreCheckoutQuery_TotalAmount
					state = fflib.FFParse_want_colon
					goto mainparse
				}

				if fflib.EqualFoldRight(ffj_key_PreCheckoutQuery_ShippingOptionID, kn) {
					currentKey = ffj_t_PreCheckoutQuery_ShippingOptionID
					state = fflib.FFParse_want_colon
					goto mainparse
				}

				if fflib.AsciiEqualFold(ffj_key_PreCheckoutQuery_OrderInfo, kn) {
					currentKey = ffj_t_PreCheckoutQuery_OrderInfo
					state = fflib.FFParse_want_colon
					goto mainparse
				}

				if fflib.AsciiEqualFold(ffj_key_PreCheckoutQuery_InvoicePayload, kn) {
					currentKey = ffj_t_PreCheckoutQuery_InvoicePayload
					state = fflib.FFParse_want_colon
					goto mainparse
				}

				if fflib.SimpleLetterEqualFold(ffj_key_PreCheckoutQuery_ID, kn) {
					currentKey = ffj_t_PreCheckoutQuery_ID
					state = fflib.FFParse_want_colon
					goto mainparse
				}

				if fflib.SimpleLetterEqualFold(ffj_key_PreCheckoutQuery_From, kn) {
					currentKey = ffj_t_PreCheckoutQuery_From
					state = fflib.FFParse_want_colon
					goto mainparse
				}

				if fflib.SimpleLetterEqualFold(ffj_key_PreCheckoutQuery_Currency, kn) {
					currentKey = ffj_t_PreCheckoutQuery_Currency
					state = fflib.FFParse_want_colon
					goto mainparse
				}

				currentKey = ffj_t_PreCheckoutQueryno_such_key
				state = fflib.FFParse_want_colon
				goto mainparse
			}

		case fflib.FFParse_want_colon:
			if tok != fflib.FFTok_colon {
				wantedTok = fflib.FFTok_colon
				goto wrongtokenerror
			}
			state = fflib.FFParse_want_value
			continue
		case fflib.FFParse_want_value:

			if tok == fflib.FFTok_left_brace || tok == fflib.FFTok_left_bracket || tok == fflib.FFTok_integer || tok == fflib.FFTok_double || tok == fflib.FFTok_string || tok == fflib.FFTok_bool || tok == fflib.FFTok_null {
				switch currentKey {

				case ffj_t_PreCheckoutQuery_Currency:
					goto handle_Currency

				case ffj_t_PreCheckoutQuery_From:
					goto handle_From

				case ffj_t_PreCheckoutQuery_ID:
					goto handle_ID

				case ffj_t_PreCheckoutQuery_InvoicePayload:
					goto handle_InvoicePayload

				case ffj_t_PreCheckoutQuery_OrderInfo:
					goto handle_OrderInfo

				case ffj_t_PreCheckoutQuery_ShippingOptionID:
					goto handle_ShippingOptionID

				case ffj_t_PreCheckoutQuery_TotalAmount:
					goto handle_TotalAmount

				case ffj_t_PreCheckoutQueryno_such_key:
					err = fs.SkipField(tok)
					if err != nil {
						return fs.WrapErr(err)
					}
					state = fflib.FFParse_after_value
					goto mainparse
				}
			} else {
				goto wantedvalue
			}
		}
	}

handle_Currency:

	/* handler: uj.Currency type=string kind=string quoted=false*/

	{

		{
			if tok != fflib.FFTok_string && tok != fflib.FFTok_null {
				return fs.WrapErr(fmt.Errorf("cannot unmarshal %s into Go value for string", tok))
			}
		}

		if tok == fflib.FFTok_null {

		} else {

			outBuf := fs.Output.Bytes()

			uj.Currency = string(string(outBuf))

		}
	}

	state = fflib.FFParse_after_value
	goto mainparse

handle_From:

	/* handler: uj.From type=models.User kind=struct quoted=false*/

	{
		/* Falling back. type=models.User kind=struct */
		tbuf, err := fs.CaptureField(tok)
		if err != nil {
			return fs.WrapErr(err)
		}

		err = json.Unmarshal(tbuf, &uj.From)
		if err != nil {
			return fs.WrapErr(err)
		}
	}

	state = fflib.FFParse_after_value
	goto mainparse

handle_ID:

	/* handler: uj.ID type=string kind=string quoted=false*/

	{

		{
			if tok != fflib.FFTok_string && tok != fflib.FFTok_null {
				return fs.WrapErr(fmt.Errorf("cannot unmarshal %s into Go value for string", tok))
			}
		}

		if tok == fflib.FFTok_null {

		} else {

			outBuf := fs.Output.Bytes()

			uj.ID = string(string(outBuf))

		}
	}

	state = fflib.FFParse_after_value
	goto mainparse

handle_InvoicePayload:

	/* handler: uj.InvoicePayload type=string kind=string quoted=false*/

	{

		{
			if tok != fflib.FFTok_string && tok != fflib.FFTok_null {
				return fs.WrapErr(fmt.Errorf("cannot unmarshal %s into Go value for string", tok))
			}
		}

		if tok == fflib.FFTok_null {

		} else {

			outBuf := fs.Output.Bytes()

			uj.InvoicePayload = string(string(outBuf))

		}
	}

	state = fflib.FFParse_after_value
	goto mainparse

handle_OrderInfo:

	/* handler: uj.OrderInfo type=models.OrderInfo kind=struct quoted=false*/

	{
		if tok == fflib.FFTok_null {

			uj.OrderInfo = nil

			state = fflib.FFParse_after_value
			goto mainparse
		}

		if uj.OrderInfo == nil {
			uj.OrderInfo = new(OrderInfo)
		}

		err = uj.OrderInfo.UnmarshalJSONFFLexer(fs, fflib.FFParse_want_key)
		if err != nil {
			return err
		}
		state = fflib.FFParse_after_value
	}

	state = fflib.FFParse_after_value
	goto mainparse

handle_ShippingOptionID:

	/* handler: uj.ShippingOptionID type=string kind=string quoted=false*/

	{

		{
			if tok != fflib.FFTok_string && tok != fflib.FFTok_null {
				return fs.WrapErr(fmt.Errorf("cannot unmarshal %s into Go value for string", tok))
			}
		}

		if tok == fflib.FFTok_null {

		} else {

			outBuf := fs.Output.Bytes()

			uj.ShippingOptionID = string(string(outBuf))

		}
	}

	state = fflib.FFParse_after_value
	goto mainparse

handle_TotalAmount:

	/* handler: uj.TotalAmount type=int64 kind=int64 quoted=false*/

	{
		if tok != fflib.FFTok_integer && tok != fflib.FFTok_null {
			return fs.WrapErr(fmt.Errorf("cannot unmarshal %s into Go value for int64", tok))
		}
	}

	{

		if tok == fflib.FFTok_null {

		} else {

			tval, err := fflib.ParseInt(fs.Output.Bytes(), 10, 64)

			if err != nil {
				return fs.WrapErr(err)
			}

			uj.TotalAmount = int64(tval)

		}
	}

	state = fflib.FFParse_after_value
	goto mainparse

wantedvalue:
	return fs.WrapErr(fmt.Errorf("wanted value token, but got token: %v", tok))
wrongtokenerror:
	return fs.WrapErr(fmt.Errorf("ffjson: wanted token: %v, but got token: %v output=%s", wantedTok, tok, fs.Output.String()))
tokerror:
	if fs.BigError != nil {
		return fs.WrapErr(fs.BigError)
	}
	err = fs.Error.ToError()
	if err != nil {
		return fs.WrapErr(err)
	}
	panic("ffjson-generated: unreachable, please report bug.")
done:

	return nil
}
