package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

// ReplyKeyboardRemove reply keyboard remove
// swagger:model ReplyKeyboardRemove
type ReplyKeyboardRemove struct {

	// remove keyboard
	RemoveKeyboard bool `json:"remove_keyboard,omitempty"`

	// selective
	Selective bool `json:"selective,omitempty"`
}

// Validate validates this reply keyboard remove
func (m *ReplyKeyboardRemove) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
