// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// SendAudioLinkBody send audio link body
// swagger:model SendAudioLinkBody
type SendAudioLinkBody struct {

	// audio
	// Required: true
	Audio *string `json:"audio"`

	// caption
	Caption string `json:"caption,omitempty"`

	// chat id
	// Required: true
	ChatID interface{} `json:"chat_id"`

	// disable notification
	DisableNotification bool `json:"disable_notification,omitempty"`

	// duration
	Duration int64 `json:"duration,omitempty"`

	// performer
	Performer string `json:"performer,omitempty"`

	// reply markup
	ReplyMarkup interface{} `json:"reply_markup,omitempty"`

	// reply to message id
	ReplyToMessageID int64 `json:"reply_to_message_id,omitempty"`

	// title
	Title string `json:"title,omitempty"`
}

// Validate validates this send audio link body
func (m *SendAudioLinkBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAudio(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateChatID(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SendAudioLinkBody) validateAudio(formats strfmt.Registry) error {

	if err := validate.Required("audio", "body", m.Audio); err != nil {
		return err
	}

	return nil
}

func (m *SendAudioLinkBody) validateChatID(formats strfmt.Registry) error {

	return nil
}

// MarshalBinary interface implementation
func (m *SendAudioLinkBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SendAudioLinkBody) UnmarshalBinary(b []byte) error {
	var res SendAudioLinkBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
