// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// SendMediaGroupLinkBody send media group link body
// swagger:model SendMediaGroupLinkBody
type SendMediaGroupLinkBody struct {

	// chat id
	// Required: true
	ChatID interface{} `json:"chat_id"`

	// disable notification
	DisableNotification bool `json:"disable_notification,omitempty"`

	// media
	// Required: true
	Media []interface{} `json:"media"`

	// reply to message id
	ReplyToMessageID int64 `json:"reply_to_message_id,omitempty"`
}

// Validate validates this send media group link body
func (m *SendMediaGroupLinkBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateChatID(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateMedia(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SendMediaGroupLinkBody) validateChatID(formats strfmt.Registry) error {

	return nil
}

func (m *SendMediaGroupLinkBody) validateMedia(formats strfmt.Registry) error {

	if err := validate.Required("media", "body", m.Media); err != nil {
		return err
	}

	for i := 0; i < len(m.Media); i++ {

	}

	return nil
}

// MarshalBinary interface implementation
func (m *SendMediaGroupLinkBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SendMediaGroupLinkBody) UnmarshalBinary(b []byte) error {
	var res SendMediaGroupLinkBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
