package updates

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/olebedev/go-tgbot/models"
)

// GetUpdatesReader is a Reader for the GetUpdates structure.
type GetUpdatesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetUpdatesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetUpdatesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetUpdatesOK creates a GetUpdatesOK with default headers values
func NewGetUpdatesOK() *GetUpdatesOK {
	return &GetUpdatesOK{}
}

/*GetUpdatesOK handles this case with default header values.

An array of Updates
*/
type GetUpdatesOK struct {
	Payload GetUpdatesOKBody
}

func (o *GetUpdatesOK) Error() string {
	return fmt.Sprintf("[GET /bot{token}/getUpdates][%d] getUpdatesOK  %+v", 200, o.Payload)
}

func (o *GetUpdatesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*GetUpdatesOKBody get updates o k body
swagger:model GetUpdatesOKBody
*/
type GetUpdatesOKBody struct {

	// description
	// Required: true
	Description *string `json:"description"`

	// error code
	// Required: true
	ErrorCode *int64 `json:"error_code"`

	// ok
	// Required: true
	Ok *bool `json:"ok"`

	// result
	// Required: true
	Result []*models.Update `json:"result"`
}
